### ISSUE TITLE
Namespace called in deployment.yaml is incorrect

### ISSUE THREAD

**Issue by keeperAndy** [Excelero/nvmesh-csi-driver#23]
Multiple references to a "nvmesh-csi-driver" namespace in ./deploy/kubernetes/deployment.yaml break deployment for both kubectl and helm because that namespace is never created. Older revs correctly call for the namespace "nvmesh-csi" and "nvmesh-csi" is the namespace referenced in all the documentation.

**Comment by gil-excelero** [comment]
Thank you for opening this issue

I updated the default namespace to `nvmesh-csi` to match the documentation

I also made updates so that helm will use the current active namespace (or the one given with the helm `--namespace` flag)
But the namespace must be created manually beforehand, I added this step to the instructions in the README file

1bcc2847bee45d9af29cc996e8a527bdb534f98b
